name: Maven Project

on: [push, pull_request]

jobs:
  run-github:
    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: Validate
        run: |
          mvn validate
          ls -lrt
      - name: Compile
        run: |
          mvn compile
          ls -lrt
      - name: Test
        run: |
          mvn test
          ls -lrt
      - name: Run Maven
        run: mvn clean package

      - name: Run Jar File
        run: java -cp target/leap-1.0-SNAPSHOT.jar first.App

      - name: upload artifact
        uses: actions/upload-artifact@v3       
        with:           
          path: target/leap-1.0-SNAPSHOT.jar
