name: Maven Project

on: [push]

jobs:
  run-github:
    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v2
      
      - name: Run Maven
        run: mvn clean package

