name: Maven Project

on: [push]

jobs:
  run-github:
    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: Validate
        run: |
          mvn validate
          ls -lrt
      - name: Validate
        run: |
          mvn compile
          ls -lrt
      - name: Test
        run: |
          mvn test
          ls -lrt
      - name: Run Maven
        run: mvn clean package
        
      - name: Run Jar File
        run: java -jar target/HelloWorldMavenProject-1.0-SNAPSHOT.jar
